language: php
php:
  - 7.0
  - 5.6
  - 5.5
  - hhvm

matrix:
  fast_finish: true

sudo: false

before_install:
    - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then phpenv config-rm xdebug.ini; fi;
    - pip install --user codecov

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --prefer-source --no-interaction

script:
    - php -dzend_extension=xdebug.so vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - codecov
